version: '3.8'

services:
  internet-clock:
    build: .
    container_name: internet-clock-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internet-clock-network

networks:
  internet-clock-network:
    driver: bridge